src/Entity/Reponse.php
<?php

namespace App\Entity;

use App\Repository\ReponseRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
#[ORM\Entity(repositoryClass: ReponseRepository::class)]
class Reponse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank (message:"Put Desc_Rec Please!")]
    private ?string $desc_rep = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank (message:"Put date Please!")]
    private ?\DateTimeInterface $date_rep = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
   
    private ?Reclamation $reclamation= null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescRep(): ?string
    {
        return $this->desc_rep;
    }

    public function setDescRep(string $desc_rep): static
    {
        $this->desc_rep = $desc_rep;

        return $this;
    }

    public function getDateRep(): ?\DateTimeInterface
    {
        return $this->date_rep;
    }

    public function setDateRep(\DateTimeInterface $date_rep): static
    {
        $this->date_rep = $date_rep;

        return $this;
    }
    public function __toString():string{
        return $this->getDescRep();
    }

    public function getReclamation(): ?Reclamation
    {
        return $this->reclamation;
    }

    public function setReclamation(?Reclamation $reclamation): static
    {
        $this->reclamation = $reclamation;

        return $this;
    }
    
}

src/Form/ReponseType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use App\Entity\Reponse;
use App\Repository\ReclamationRepository;
use App\Repository\RendezVousRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints as Assert;
class ReponseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('desc_rep', TextType::class, [
                'label' => 'Description',
                'attr' => [
                    'placeholder' => 'Your response',
                ],
                'constraints' => [
                    new Assert\NotBlank(['message' => 'Please enter a description']),
                ],
            ])
            ->add('date_rep', DateType::class, [
                'label' => 'Date',
                'format' => 'yyyy-MM-dd',
                'constraints' => [
                    new Assert\NotBlank(['message' => 'Please enter a date']),
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reponse::class,
        ]);
    }
}

src/Controller/ReponseController.php
<?php

namespace App\Controller;

use App\Entity\Reponse;
use App\Form\ReponseType;
use App\Repository\ReclamationRepository;
use App\Repository\ReponseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/reponse')]
class ReponseController extends AbstractController
{
    #[Route('/', name: 'app_reponse_index', methods: ['GET'])]
    public function index(ReponseRepository $reponseRepository): Response
    {
        return $this->render('reponse/index.html.twig', [
            'reponses' => $reponseRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_reponse_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ManagerRegistry $managerRegistry): Response
    {
        $em = $managerRegistry->getManager();
        $reponse = new Reponse();
        $form = $this->createForm(ReponseType::class, $reponse);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($reponse);
            $em->flush();

            return $this->redirectToRoute('app_reponse_index');
        }

        return $this->renderForm('reponse/new.html.twig', [
            'reponse' => $reponse,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reponse_show', methods: ['GET'])]
    public function show(Reponse $reponse): Response
    {
        return $this->render('reponse/show.html.twig', [
            'reponse' => $reponse,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reponse_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reponse $reponse, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ReponseType::class, $reponse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_reponse_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reponse/edit.html.twig', [
            'reponse' => $reponse,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reponse_delete', methods: ['POST'])]
    public function delete(Request $request, Reponse $reponse, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $reponse->getId(), $request->request->get('_token'))) {
            $entityManager->remove($reponse);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_reponse_index', [], Response::HTTP_SEE_OTHER);
    }
    #[Route('/create-response/{reclamationId}', name: 'create_response_for_reclamation', methods: ['GET', 'POST'])]
    public function createResponseForReclamation(Request $request, EntityManagerInterface $entityManager, ReclamationRepository $reclamationRepository, int $reclamationId): Response
    {
        $reclamation = $reclamationRepository->find($reclamationId);

        if (!$reclamation) {
            throw $this->createNotFoundException('Reclamation not found');
        }

        $reponse = new Reponse();
        $reponse->setReclamation($reclamation); // Set the Reclamation field directly

        $form = $this->createForm(ReponseType::class, $reponse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reponse);
            $entityManager->flush();

            return $this->redirectToRoute('app_reclamation_show', ['id' => $reclamation->getId()]);
        }

        return $this->renderForm('reponse/new.html.twig', [
            'reponse' => $reponse,
            'form' => $form,
        ]);
    }
}

templates/reponse/_delete_form.html.twig
<form method="post" action="{{ path('app_reponse_delete', {'id': reponse.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reponse.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reponse/_form.html.twig
{% extends "back.html.twig" %} {% block title %}RadioHub | response {% endblock
%} {% block body %}

<div class="container-fluid">
    <div class="card">
        <div class="card-body">
        <h1>Create new Response</h1>
      {{ form_start(form,{'attr':{'novalidate':'novalidate','class':'w-100'}}) }}

      
    <div class="d-flex" style="gap: .5rem;">
      <div class="d-flex flex-column w-100">
        {{ form_widget(form.desc_rep, {'attr': {'class': 'form-control'   }}) }}
        {{ form_errors(form.desc_rep,{'attr':{'class':'text-danger'}}) }}
      </div>
      <div class="d-flex flex-column w-100">
        {{ form_widget(form.date_rep, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.date_rep,{'attr':{'class':'text-danger'}}) }}
      </div>
    </div>



      <button type="submit" class="btn btn-primary">Send</button>
      {{ form_end(form) }}
    </div>
  </div>
</div>

{%endblock%}

templates/reponse/edit.html.twig
{% block title %}Edit response{% endblock %}

{% block body %}
    <h1>Edit Reponse</h1>

    {{ include('reponse/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reponse_index') }}">back to list</a>

    {{ include('reponse/_delete_form.html.twig') }}
{% endblock %}

templates/reponse/index.html.twig
{% extends "back.html.twig" %}

{% block title %} Response {% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="card">
        <div class="card-body">
    <h1>Responses</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Desc_rep</th>
                <th>Date_rep</th>
                <th colspan="2">actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reponse in reponses %}
            <tr>
                <td>{{ reponse.id }}</td>
                <td>{{ reponse.descRep }}</td>
                <td>{{ reponse.dateRep ? reponse.dateRep|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a  class="btn btn-primary" href="{{ path('app_reponse_show', {'id': reponse.id}) }}">show</a>
                    <td>
                    <a  class="btn btn-success" href="{{ path('app_reponse_edit', {'id': reponse.id}) }}">edit</a>
                </td>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

  
        </div></div></div>
{% endblock %}

templates/reponse/new.html.twig
{# reponse/new.html.twig #}
{% block body %}
   

    {{ include('reponse/_form.html.twig') }}

    {# Access properties of the Reponse object, not the form view #}
    
  
    

    <a href="{{ path('app_reclamation_show', {'id': reponse.reclamation.id}) }}">Back to Reclamation</a>
{% endblock %}

templates/reponse/show.html.twig
{% extends "back.html.twig" %}

{% block title %}Reponse{% endblock %}

{% block body %}
    <h1>Reponse</h1>
    <div style="justify-content: center!important; ">
    <table class="table">
       
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reponse.id }}</td>
            </tr>
            <tr>
                <th>Desc_rep</th>
                <td>{{ reponse.descRep }}</td>
            </tr>
            <tr>
                <th>Date_rep</th>
                <td>{{ reponse.dateRep ? reponse.dateRep|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>

    </table>
</div>
    <a href="{{ path('app_reponse_index') }}">back to list</a>

    <a href="{{ path('app_reponse_edit', {'id': reponse.id}) }}">edit</a>

    {{ include('reponse/_delete_form.html.twig') }}
{% endblock %}