src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;


#[ORM\Entity(repositoryClass: ReclamationRepository::class)]
class Reclamation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $id_user = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Put State Please!")]
    private ?bool $etat_rec = false;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    //#[Gedmo\Timestampable(on: "create")]
    private ?\DateTimeInterface $date_rec = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Put Desc_Rec Please!")]
    private ?string $desc_rec = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Put Type Please!")]

    private ?string $type_rec = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUser(): ?string
    {
        return $this->id_user;
    }

    public function setIdUser(string $id_user): static
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function isEtatRec(): ?bool
    {
        return $this->etat_rec;
    }

    public function setEtatRec(bool $etat_rec): static
    {
        $this->etat_rec = $etat_rec;

        return $this;
    }

    public function getDateRec(): ?\DateTimeInterface
    {
        return $this->date_rec;
    }

    public function setDateRec(\DateTimeInterface $date_rec): static
    {
        $this->date_rec = $date_rec;

        return $this;
    }

    public function getDescRec(): ?string
    {
        return $this->desc_rec;
    }

    public function setDescRec(string $desc_rec): static
    {
        $this->desc_rec = $desc_rec;

        return $this;
    }

    public function getTypeRec(): ?string
    {
        return $this->type_rec;
    }

    public function setTypeRec(string $type_rec): static
    {
        $this->type_rec = $type_rec;

        return $this;
    }
    public function __construct()
    {
        $this->etat_rec = false;
    }
}

src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use VictorPrdh\RecaptchaBundle\Form\ReCaptchaType;

class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id_user',TextType::class,
            [
                'label' => false,
                'attr' => ['placeholder' => 'votre ID'],

                
            ])
        
            ->add('date_rec', DateType::class,
            [
                'label' => false,
                // 'widget' => 'single_text', // This ensures a single text input without a date picker
                
               'widget' => 'single_text', // This ensures a single text input without a date picker
               'format' => 'yyyy-MM-dd', // Adjust the format as needed
            ])
            ->add('desc_rec',TextType::class,
            [
                'label' => false,
                'attr' => ['placeholder' => ' Add a description'],

                
            ])
            ->add('type_rec', ChoiceType::class, [
                'choices' => [
                    'Select type reclamation...' => '', 
                    'Service_Client' => 'Service_Client',
                    'Systeme' => 'Systeme',
                    'Equipements' => 'Equipements',
                  
                ],
                'label' => false,
            ])
        
          
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;

use App\Entity\Reclamation;
use App\Form\ReclamationType;
use App\Entity\Reponse;
use Knp\Component\Pager\PaginatorInterface;
use App\Repository\ReponseRepository;
use App\Repository\ReclamationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;

#[Route('/reclamation')]
class ReclamationController extends AbstractController
{
    #[Route('/', name: 'app_reclamation_index', methods: ['GET'])]
    public function index(ReclamationRepository $reclamationRepository, Request $request, PaginatorInterface $paginator, ReponseRepository $resrepo): Response
    {

        $reclamation = $reclamationRepository->findAll();
        $responses = $resrepo->findAll();
       

        $reclamation = $paginator->paginate(
            $reclamation,
            $request->query->getInt('page', 1),
            //limit per page
            3
        );

        return $this->render('reclamation/index.html.twig', [
            'reclamations' => $reclamation,
            'reponses' => $responses

        ]);
    }

    #[Route('/success', name: 'app_sucess_reclamtaion', methods: ['GET', 'POST'])]
    public function success(): Response
    {
        return $this->render('reclamation/sucess.html.twig');
    }

    #[Route('/new', name: 'app_reclamation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $reclamation = new Reclamation();
        $reclamation->setEtatRec(true); // Set the isEtatRec field to false

        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reclamation);
            $entityManager->flush();

            return $this->redirectToRoute('app_sucess_reclamtaion');
        }

        return $this->renderForm('reclamation/new.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form,
        ]);
    }
    #[Route('/{id}', name: 'app_reclamation_show', methods: ['GET'])]
    public function show(Reclamation $reclamation): Response
    {
        return $this->render('reclamation/show.html.twig', [
            'reclamation' => $reclamation,
        ]);
    }



    /////////////////edit////////

    #[Route('/{id}/edit', name: 'app_reclamation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reclamation $reclamation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reclamation/edit.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reclamation_delete', methods: ['POST'])]
    public function delete($id, Request $request, Reclamation $reclamation, EntityManagerInterface $entityManager, ReponseRepository $resrepo): Response
    {
        if ($this->isCsrfTokenValid('delete' . $reclamation->getId(), $request->request->get('_token'))) {
            // Get the associated Reponse
            $reponse = $resrepo->findOneBy(['reclamation' => $reclamation]);

            // Remove the associated Reponse, if it exists
            if ($reponse !== null) {
                $entityManager->remove($reponse);
            }

            // Remove the Reclamation
            $entityManager->remove($reclamation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reclamation/_delete_form.html.twig
<form method="post" action="{{ path('app_reclamation_delete', {'id': reclamation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reclamation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reclamation/_form.html.twig
{% extends "front.html.twig" %} {% block title %}RadioHub | Claims{% endblock %}
{% block body %}
<style>
    form{
        background-color: #D9D9D9;
        padding: 20px;border-radius: 8px;
    }
</style>
<div class="d-flex w-100" style="gap: 2rem; padding:3rem;">

<img style="height: 300px;object-fit: cover;" src="../../front/img/IRM_illustration_.jpg" alt="img">


{{ form_start(form,{'attr':{'novalidate':'novalidate','class':'w-100'}})}}

<div style="gap: 1rem;" class="d-flex flex-column w-100 mx-auto">
    <h1 class="text-center my-5">Add Claim</h1>
  <div class="d-flex" style="gap: .5rem;">
    <div class="d-flex flex-column w-100">
      {{ form_widget(form.id_user, {'attr': {'class': 'form-control' }}) }}
      {{ form_errors(form.id_user,{'attr':{'class':'text-danger'}}) }}
    </div>
    
  </div>
  <div class="d-flex" style="gap: .5rem;">
    <div class="d-flex flex-column w-100">
      {{ form_widget(form.date_rec, {'attr': {'class': 'd-flex',   }}) }}
      {{ form_errors(form.date_rec,{'attr':{'class':'text-danger'}}) }}
    </div>  </div>
    <div class="d-flex flex-column w-100">
      {{ form_widget(form.desc_rec, {'attr': {'class': 'form-control',   }}) }}
      {{ form_errors(form.desc_rec,{'attr':{'class':'text-danger'}}) }}
    </div>

  <div class="d-flex" style="gap: .5rem;">
    <div class="d-flex flex-column w-100">
      {{ form_widget(form.type_rec, {'attr': {'class': 'form-control'   }}) }}
      {{ form_errors(form.type_rec,{'attr':{'class':'text-danger'}}) }}
    </div>
    
  </div>
  <button type="submit" class="btn btn-primary mx-auto w-25">Send</button>
</div>

{{ form_end(form) }}
</div>

{%endblock%} {% block footer %} {% endblock %}

templates/reclamation/edit.html.twig
{% extends "back.html.twig" %}

{% block title %}Edit Reclamation{% endblock %}

{% block body %}
    <h1>Edit Reclamation</h1>

    {{ include('reclamation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reclamation_index') }}">back to list</a>

    {{ include('reclamation/_delete_form.html.twig') }}
{% endblock %}

templates/reclamation/index.html.twig
{% extends 'back.html.twig' %}

{% block title %}Reclamation{% endblock %}

{% block body %}
    <h1>Reclamation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_user</th>
                <th>Etat_rec</th>
                <th>Date_rec</th>
                <th>Desc_rec</th>
                <th>Type_rec</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reclamation in reclamations %}
            <tr>
                <td>{{ reclamation.id }}</td>
                <td>{{ reclamation.idUser }}</td>
                <td>{{ reclamation.etatRec ? 'Yes' : 'No' }}</td>
                <td>{{ reclamation.dateRec ? reclamation.dateRec|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ reclamation.descRec }}</td>
                <td>{{ reclamation.typeRec }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('app_reclamation_show', {'id': reclamation.id}) }}">show</a>
                    <a class="btn btn-secondary" href="{{ path('app_reclamation_edit', {'id': reclamation.id}) }}">edit</a>

                    
                    
                    
                        {% if reponses == null %}
                        <a class="btn btn-secondary" href="{{ path('create_response_for_reclamation', {'reclamationId': reclamation.id}) }}">Response</a>
                        {% endif %}

                    {%for reponses in reponses %}
                    {% if reponses.reclamation.id != reclamation.id  %}
                    <a class="btn btn-secondary" href="{{ path('create_response_for_reclamation', {'reclamationId': reclamation.id}) }}">Response</a>
                    {%else%}
                    {% endif %}
                    {% endfor %}
                    
                    





                    

                 
                 

                  
                
                    
                    

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('app_reclamation_new') }}">Create new</a>

    {{ knp_pagination_render(reclamations) }}  
{% endblock %}

templates/reclamation/new.html.twig
{% block body %}

    {{ include('reclamation/_form.html.twig') }}

{% endblock %}

templates/reclamation/show.html.twig
{% extends "back.html.twig" %}

{% block title %}Reclamation{% endblock %}

{% block body %}
    <h1>Reclamations</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reclamation.id }}</td>
            </tr>
            <tr>
                <th>Id_user</th>
                <td>{{ reclamation.idUser }}</td>
            </tr>
            <tr>
                <th>Etat_rec</th>
                <td>{{ reclamation.etatRec ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Date_rec</th>
                <td>{{ reclamation.dateRec ? reclamation.dateRec|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Desc_rec</th>
                <td>{{ reclamation.descRec }}</td>
            </tr>
            <tr>
                <th>Type_rec</th>
                <td>{{ reclamation.typeRec }}</td>
            </tr>
        </tbody>
    </table>

    <a class:'btn btn-secondary' href="{{ path('app_reclamation_index') }}">back to list</a>

    <a class:'btn btn-secondary' href="{{ path('app_reclamation_edit', {'id': reclamation.id}) }}">edit</a>

    {{ include('reclamation/_delete_form.html.twig') }}
{% endblock %}

templates/reclamation/sucess.html.twig
{% extends 'front.html.twig' %}

{% block body %}
<h1 class="text-center mt-5"> 🎆 Added successfully 🎆</h1>
<center>

    <a class="text-center my-5 " class="btn btn-success" href="{{ path('app_home')}}">Go Back To HomePage</a>
</center>
{% endblock %}
{% block footer %}
{% endblock %}